### ISSUE TITLE
Colours not shown in they include alpha component

### ISSUE THREAD

**Issue by tarasis** [willofindie/vscode-cssvar#28]
When adding an alpha component to hsl the color isn't shown in the intellisense window, or beside the CSS selector.

```css
    --col-test-white: hsl(0 0% 100%);
    --col-test-hsl-with-alpha: hsl(0 0% 100% / 1);
    --col-test-hsla: hsla(0, 0%, 100%, 1);
    --col-test-rbg-with-alpha: rgb(255 255 255 / 1);
    --col-test-rgba: rgba(255, 255, 255, 1);
    --col-test-rgb-no-alpha: rgb(255, 255, 255);
```

Actually it seems to be an issue with parsing, because that last variable doesn't have the white shown either

<img width="379" alt="Screenshot 2022-03-28 at 22 04 49" src="https://user-images.githubusercontent.com/3006/160487030-f7e949ce-dd4b-4d20-8d8e-8f0a089e71b6.png">

And it seems to generate duplicate entries in the intellisense window

<img width="437" alt="Screenshot 2022-03-28 at 22 04 03" src="https://user-images.githubusercontent.com/3006/160487166-6859944f-81f1-4b3c-9282-0c8079e3f35c.png">

Changing all the variables to use , separated values doesn't help. Indeed it makes it slightly worse as ```color: var(--col-test-hsl-with-alpha);``` no longer shows a color.

```css
    --col-test-white: hsl(0, 0%, 100%);
    --col-test-hsl-with-alpha: hsl(0, 0%, 100%, 1);
    --col-test-hsla: hsla(0, 0%, 100%, 1);
    --col-test-rbg-with-alpha: rgb(255, 255, 255, 1);
    --col-test-rgba: rgba(255, 255, 255, 1);
    --col-test-rgb-no-alpha: rgb(255, 255, 255);
```

<img width="465" alt="Screenshot 2022-03-28 at 22 11 24" src="https://user-images.githubusercontent.com/3006/160487901-58eb482d-911c-43ec-bb6e-e0bb3bbe8193.png">

--- 

I am using VS Code 1.65.2 (on macOS 12.3), and 1.30 of your extension.

**Comment by phoenisx** [comment]
Thanks for such a thorough explanation of the issue.

I verified the issue and it has regressed since the last release `v1.30`.

**_I will raise a bug fix by tonight, to fix the color not showing._**

Regarding duplicate variables, I feel you have kept duplicate CSS variables in different selector blocks. Since variables from each selector are considered unique (because variables can be locally scoped to a selector as well), the extension doesn't remove the duplicates.

Duplicates in the same selector are always removed.

If you are using duplicate variables to support Theming on your website, you should read [Theming support to remove duplicate theme variables](https://github.com/willofindie/vscode-cssvar/blob/master/theming.md).

**Let me know if there is any other bug you have faced with this extension.**

Thanks for your support and for using this extension. 🙇🏾

**Comment by tarasis** [comment]
Awesome, thank you.

Regards the duplicate values, this was something I had failed to turned off. (I wasn't aware I could/should)

I needed to tell VScode not to show the variables.

```json
"[css]" : {
    "editor.suggest.showVariables": false
  },
```

Now VScode only shows your options.

**Comment by phoenisx** [comment]
```
"[css]" : {
    "editor.suggest.showVariables": false
  },
```

☝🏾 Even I didn't know that. Thanks for letting me know.

Also, I have released 1.4.0 with the fix for the above issue.

Do let me know if you find any other issue or regression 👍🏾

**Comment by lucianahanan** [comment]
This solution of disabling the suggest, didn't do anything for me here. The suggestion list still shows a bunch of variables that are not in the current file.

**Comment by tarasis** [comment]
@lucianahanan It had worked at one point, but now it doesn't work and indeed setting that setting to false stops this extension from showing any variables EXCEPT color/colour.

I desperately want a way to get VSCode to only ever offer the suggestions from this extension when working in a file with CSS variables ... or change my working so all variables go in a variables.css file which might be easier at this stage.
